FROM node:12-alpine as builder

WORKDIR /app
COPY package.json /app/package.json
RUN yarn install
COPY . /app
RUN yarn build-client


# production environment
FROM nginx:1.16.0-alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]